// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd8bBFLERPMzubHscjJvG1KTqSYMKbENw',
    appId: '1:298816933849:web:aa54a34166543e65a513c8',
    messagingSenderId: '298816933849',
    projectId: 'booking-dashboard-2edae',
    authDomain: 'booking-dashboard-2edae.firebaseapp.com',
    storageBucket: 'booking-dashboard-2edae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYoU-DxGF9tmWjQtgYxIonW01q60kRCZY',
    appId: '1:298816933849:android:d7ee8d121062c7cba513c8',
    messagingSenderId: '298816933849',
    projectId: 'booking-dashboard-2edae',
    storageBucket: 'booking-dashboard-2edae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAidmBfm4hOOFFPohMcuNMtTFqL1n2YtrE',
    appId: '1:298816933849:ios:f02c4ec62d898b09a513c8',
    messagingSenderId: '298816933849',
    projectId: 'booking-dashboard-2edae',
    storageBucket: 'booking-dashboard-2edae.appspot.com',
    androidClientId: '298816933849-j2ule98q3dljl9mn1fvms5b20415kt9i.apps.googleusercontent.com',
    iosClientId: '298816933849-df8vl032e4k7derlint3p10sqfhd9qhd.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAidmBfm4hOOFFPohMcuNMtTFqL1n2YtrE',
    appId: '1:298816933849:ios:f02c4ec62d898b09a513c8',
    messagingSenderId: '298816933849',
    projectId: 'booking-dashboard-2edae',
    storageBucket: 'booking-dashboard-2edae.appspot.com',
    androidClientId: '298816933849-j2ule98q3dljl9mn1fvms5b20415kt9i.apps.googleusercontent.com',
    iosClientId: '298816933849-df8vl032e4k7derlint3p10sqfhd9qhd.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboard',
  );
}
